# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(930, 640)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_main = QtWidgets.QWidget(self.centralwidget)
        self.widget_main.setStyleSheet("QWidget#widget_main{border-radius:2px;background:qlineargradient(spread:pad,x1:0,y1:0,x2:1,y2:0,stop:0 #FFFFFF,stop:1 #FFFFFF);}")
        self.widget_main.setObjectName("widget_main")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_main)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_bar = QtWidgets.QWidget(self.widget_main)
        self.widget_bar.setMinimumSize(QtCore.QSize(40, 0))
        self.widget_bar.setMaximumSize(QtCore.QSize(40, 16777215))
        self.widget_bar.setStyleSheet("QWidget#widget_bar{border-radius:0px;background-color:rgba(90,135,228,0.3);}")
        self.widget_bar.setObjectName("widget_bar")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_bar)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_face = QtWidgets.QLabel(self.widget_bar)
        self.label_face.setMinimumSize(QtCore.QSize(30, 30))
        self.label_face.setMaximumSize(QtCore.QSize(30, 30))
        self.label_face.setText("")
        self.label_face.setAlignment(QtCore.Qt.AlignCenter)
        self.label_face.setObjectName("label_face")
        self.verticalLayout.addWidget(self.label_face)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.widget_2 = QtWidgets.QWidget(self.widget_bar)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_notify_at = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_notify_at.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_notify_at.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_notify_at.setStyleSheet("QPushButton{border-image:url(:/images/unread.png);background-color:rgba(90,135,228,0.5);color:white;border:0px solid grey;border-radius:2px;}QPushButton:hover{background-color:rgba(90,135,228,0.3);border-radius:2px;}")
        self.pushButton_notify_at.setText("")
        self.pushButton_notify_at.setObjectName("pushButton_notify_at")
        self.verticalLayout_3.addWidget(self.pushButton_notify_at)
        self.pushButton_notify_chat = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_notify_chat.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_notify_chat.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_notify_chat.setStyleSheet("QPushButton{border-image:url(:/images/unread.png);background-color:rgba(90,135,228,0.5);color:white;border:0px solid grey;border-radius:2px;}QPushButton:hover{background-color:rgba(90,135,228,0.3);border-radius:2px;}")
        self.pushButton_notify_chat.setText("")
        self.pushButton_notify_chat.setObjectName("pushButton_notify_chat")
        self.verticalLayout_3.addWidget(self.pushButton_notify_chat)
        self.pushButton_notify_reply = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_notify_reply.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_notify_reply.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_notify_reply.setStyleSheet("QPushButton{border-image:url(:/images/unread.png);background-color:rgba(90,135,228,0.5);color:white;border:0px solid grey;border-radius:2px;}QPushButton:hover{background-color:rgba(90,135,228,0.3);border-radius:2px;}")
        self.pushButton_notify_reply.setText("")
        self.pushButton_notify_reply.setObjectName("pushButton_notify_reply")
        self.verticalLayout_3.addWidget(self.pushButton_notify_reply)
        self.pushButton_notify_like = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_notify_like.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_notify_like.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_notify_like.setStyleSheet("QPushButton{border-image:url(:/images/unread.png);background-color:rgba(90,135,228,0.5);color:white;border:0px solid grey;border-radius:2px;}QPushButton:hover{background-color:rgba(90,135,228,0.3);border-radius:2px;}")
        self.pushButton_notify_like.setText("")
        self.pushButton_notify_like.setObjectName("pushButton_notify_like")
        self.verticalLayout_3.addWidget(self.pushButton_notify_like)
        self.pushButton_notify_sys_msg = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_notify_sys_msg.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_notify_sys_msg.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_notify_sys_msg.setStyleSheet("QPushButton{border-image:url(:/images/unread.png);background-color:rgba(90,135,228,0.5);color:white;border:0px solid grey;border-radius:2px;}QPushButton:hover{background-color:rgba(90,135,228,0.3);border-radius:2px;}")
        self.pushButton_notify_sys_msg.setText("")
        self.pushButton_notify_sys_msg.setObjectName("pushButton_notify_sys_msg")
        self.verticalLayout_3.addWidget(self.pushButton_notify_sys_msg)
        self.verticalLayout.addWidget(self.widget_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.widget = QtWidgets.QWidget(self.widget_bar)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_simple = QtWidgets.QPushButton(self.widget)
        self.pushButton_simple.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_simple.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_simple.setStyleSheet("QPushButton{background-color:rgba(90,135,228,0.5);color:white;border:0px solid grey;border-radius:2px;}QPushButton:hover{background-color:rgba(90,135,228,0.3);border-radius:2px;}")
        self.pushButton_simple.setText("")
        self.pushButton_simple.setObjectName("pushButton_simple")
        self.verticalLayout_2.addWidget(self.pushButton_simple)
        self.pushButton_signout = QtWidgets.QPushButton(self.widget)
        self.pushButton_signout.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_signout.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_signout.setStyleSheet("QPushButton{background-color:rgba(90,135,228,0.5);color:white;border:0px solid grey;border-radius:2px;}QPushButton:hover{background-color:rgba(90,135,228,0.3);border-radius:2px;}")
        self.pushButton_signout.setText("")
        self.pushButton_signout.setObjectName("pushButton_signout")
        self.verticalLayout_2.addWidget(self.pushButton_signout)
        self.pushButton_close = QtWidgets.QPushButton(self.widget)
        self.pushButton_close.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_close.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_close.setStyleSheet("QPushButton{background-color:rgba(90,135,228,0.5);color:white;border:0px solid grey;border-radius:2px;}QPushButton:hover{background-color:rgba(90,135,228,0.3);border-radius:2px;}")
        self.pushButton_close.setText("")
        self.pushButton_close.setObjectName("pushButton_close")
        self.verticalLayout_2.addWidget(self.pushButton_close)
        self.verticalLayout.addWidget(self.widget)
        self.horizontalLayout.addWidget(self.widget_bar)
        self.widget_left = QtWidgets.QWidget(self.widget_main)
        self.widget_left.setMinimumSize(QtCore.QSize(280, 0))
        self.widget_left.setMaximumSize(QtCore.QSize(280, 16777215))
        self.widget_left.setStyleSheet("QWidget#widget_left{background:#F0F5FF;border-bottom-left-radius:2px;border-right-width:0px;border-style:solid;border-color:rgba(69,104,220,0.3);}")
        self.widget_left.setObjectName("widget_left")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget_left)
        self.gridLayout_5.setContentsMargins(0, 10, 0, 10)
        self.gridLayout_5.setHorizontalSpacing(7)
        self.gridLayout_5.setVerticalSpacing(10)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.widget_level = QtWidgets.QWidget(self.widget_left)
        self.widget_level.setStyleSheet("QWidget#widget_level{background:rgba(255,255,255,0.5);border-bottom-right-radius:2px;}")
        self.widget_level.setObjectName("widget_level")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_level)
        self.gridLayout_2.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_brokerage = QtWidgets.QLabel(self.widget_level)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_brokerage.setFont(font)
        self.label_brokerage.setAlignment(QtCore.Qt.AlignCenter)
        self.label_brokerage.setObjectName("label_brokerage")
        self.gridLayout_2.addWidget(self.label_brokerage, 3, 2, 1, 1)
        self.label_balance = QtWidgets.QLabel(self.widget_level)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_balance.setFont(font)
        self.label_balance.setAlignment(QtCore.Qt.AlignCenter)
        self.label_balance.setObjectName("label_balance")
        self.gridLayout_2.addWidget(self.label_balance, 3, 1, 1, 1)
        self.label_coins = QtWidgets.QLabel(self.widget_level)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_coins.setFont(font)
        self.label_coins.setAlignment(QtCore.Qt.AlignCenter)
        self.label_coins.setObjectName("label_coins")
        self.gridLayout_2.addWidget(self.label_coins, 3, 0, 1, 1)
        self.label_default_bp = QtWidgets.QLabel(self.widget_level)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_default_bp.setFont(font)
        self.label_default_bp.setAlignment(QtCore.Qt.AlignCenter)
        self.label_default_bp.setObjectName("label_default_bp")
        self.gridLayout_2.addWidget(self.label_default_bp, 3, 3, 1, 1)
        self.progressBar_exp = QtWidgets.QProgressBar(self.widget_level)
        self.progressBar_exp.setMaximumSize(QtCore.QSize(16777215, 10))
        self.progressBar_exp.setStyleSheet("QProgressBar::chunk{background:qlineargradient(spread:pad,x1:0,y1:0,x2:1,y2:0,stop:0 #36d1dc,stop:1 #5b86e5);}")
        self.progressBar_exp.setProperty("value", 24)
        self.progressBar_exp.setTextVisible(False)
        self.progressBar_exp.setObjectName("progressBar_exp")
        self.gridLayout_2.addWidget(self.progressBar_exp, 2, 0, 1, 4)
        self.label_level_exp = QtWidgets.QLabel(self.widget_level)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.label_level_exp.setFont(font)
        self.label_level_exp.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_level_exp.setObjectName("label_level_exp")
        self.gridLayout_2.addWidget(self.label_level_exp, 0, 2, 1, 2)
        self.label_level = QtWidgets.QLabel(self.widget_level)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.label_level.setFont(font)
        self.label_level.setObjectName("label_level")
        self.gridLayout_2.addWidget(self.label_level, 0, 0, 1, 2)
        self.gridLayout_5.addWidget(self.widget_level, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 265, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem2, 4, 0, 1, 1)
        self.pushButton_notify = QtWidgets.QPushButton(self.widget_left)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.pushButton_notify.setFont(font)
        self.pushButton_notify.setStyleSheet("QPushButton{border:0px solid grey;border-radius:2px;}")
        self.pushButton_notify.setObjectName("pushButton_notify")
        self.gridLayout_5.addWidget(self.pushButton_notify, 5, 0, 1, 1)
        self.widget_article_sum = QtWidgets.QWidget(self.widget_left)
        self.widget_article_sum.setStyleSheet("QWidget#widget_article_sum{background:rgba(255,255,255,0.5);border-bottom-right-radius:2px;}")
        self.widget_article_sum.setObjectName("widget_article_sum")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget_article_sum)
        self.gridLayout_4.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_4.setSpacing(5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_article_view = QtWidgets.QLabel(self.widget_article_sum)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_article_view.setFont(font)
        self.label_article_view.setAlignment(QtCore.Qt.AlignCenter)
        self.label_article_view.setObjectName("label_article_view")
        self.gridLayout_4.addWidget(self.label_article_view, 1, 0, 1, 1)
        self.label_article_like = QtWidgets.QLabel(self.widget_article_sum)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_article_like.setFont(font)
        self.label_article_like.setAlignment(QtCore.Qt.AlignCenter)
        self.label_article_like.setObjectName("label_article_like")
        self.gridLayout_4.addWidget(self.label_article_like, 1, 1, 1, 1)
        self.label_article_coin = QtWidgets.QLabel(self.widget_article_sum)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_article_coin.setFont(font)
        self.label_article_coin.setAlignment(QtCore.Qt.AlignCenter)
        self.label_article_coin.setObjectName("label_article_coin")
        self.gridLayout_4.addWidget(self.label_article_coin, 1, 2, 1, 1)
        self.label_article_reply = QtWidgets.QLabel(self.widget_article_sum)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_article_reply.setFont(font)
        self.label_article_reply.setAlignment(QtCore.Qt.AlignCenter)
        self.label_article_reply.setObjectName("label_article_reply")
        self.gridLayout_4.addWidget(self.label_article_reply, 1, 3, 1, 1)
        self.label_article_share = QtWidgets.QLabel(self.widget_article_sum)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_article_share.setFont(font)
        self.label_article_share.setAlignment(QtCore.Qt.AlignCenter)
        self.label_article_share.setObjectName("label_article_share")
        self.gridLayout_4.addWidget(self.label_article_share, 2, 0, 1, 1)
        self.label_article_favorite = QtWidgets.QLabel(self.widget_article_sum)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_article_favorite.setFont(font)
        self.label_article_favorite.setAlignment(QtCore.Qt.AlignCenter)
        self.label_article_favorite.setObjectName("label_article_favorite")
        self.gridLayout_4.addWidget(self.label_article_favorite, 2, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.widget_article_sum)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(8)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_4.addWidget(self.label_17, 0, 0, 1, 4)
        self.gridLayout_5.addWidget(self.widget_article_sum, 3, 0, 1, 1)
        self.widget_rating = QtWidgets.QWidget(self.widget_left)
        self.widget_rating.setStyleSheet("QWidget#widget_rating{background:rgba(255,255,255,0.5);border-bottom-right-radius:2px;}")
        self.widget_rating.setObjectName("widget_rating")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.widget_rating)
        self.gridLayout_6.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_6.setSpacing(5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_follower = QtWidgets.QLabel(self.widget_rating)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_follower.setFont(font)
        self.label_follower.setAlignment(QtCore.Qt.AlignCenter)
        self.label_follower.setObjectName("label_follower")
        self.gridLayout_6.addWidget(self.label_follower, 0, 0, 1, 1)
        self.label_creative = QtWidgets.QLabel(self.widget_rating)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_creative.setFont(font)
        self.label_creative.setAlignment(QtCore.Qt.AlignCenter)
        self.label_creative.setObjectName("label_creative")
        self.gridLayout_6.addWidget(self.label_creative, 0, 1, 1, 1)
        self.label_influence = QtWidgets.QLabel(self.widget_rating)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_influence.setFont(font)
        self.label_influence.setAlignment(QtCore.Qt.AlignCenter)
        self.label_influence.setObjectName("label_influence")
        self.gridLayout_6.addWidget(self.label_influence, 0, 2, 1, 1)
        self.label_credit = QtWidgets.QLabel(self.widget_rating)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_credit.setFont(font)
        self.label_credit.setAlignment(QtCore.Qt.AlignCenter)
        self.label_credit.setObjectName("label_credit")
        self.gridLayout_6.addWidget(self.label_credit, 0, 3, 1, 1)
        self.gridLayout_5.addWidget(self.widget_rating, 1, 0, 1, 1)
        self.widget_video_sum = QtWidgets.QWidget(self.widget_left)
        self.widget_video_sum.setStyleSheet("QWidget#widget_video_sum{background:rgba(255,255,255,0.5);border-bottom-right-radius:2px;}")
        self.widget_video_sum.setObjectName("widget_video_sum")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_video_sum)
        self.gridLayout_3.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_3.setSpacing(5)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_video_view = QtWidgets.QLabel(self.widget_video_sum)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_video_view.setFont(font)
        self.label_video_view.setAlignment(QtCore.Qt.AlignCenter)
        self.label_video_view.setObjectName("label_video_view")
        self.gridLayout_3.addWidget(self.label_video_view, 1, 0, 1, 1)
        self.label_video_like = QtWidgets.QLabel(self.widget_video_sum)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_video_like.setFont(font)
        self.label_video_like.setAlignment(QtCore.Qt.AlignCenter)
        self.label_video_like.setObjectName("label_video_like")
        self.gridLayout_3.addWidget(self.label_video_like, 1, 1, 1, 1)
        self.label_video_coin = QtWidgets.QLabel(self.widget_video_sum)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_video_coin.setFont(font)
        self.label_video_coin.setAlignment(QtCore.Qt.AlignCenter)
        self.label_video_coin.setObjectName("label_video_coin")
        self.gridLayout_3.addWidget(self.label_video_coin, 1, 2, 1, 1)
        self.label_video_reply = QtWidgets.QLabel(self.widget_video_sum)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_video_reply.setFont(font)
        self.label_video_reply.setAlignment(QtCore.Qt.AlignCenter)
        self.label_video_reply.setObjectName("label_video_reply")
        self.gridLayout_3.addWidget(self.label_video_reply, 1, 3, 1, 1)
        self.label_video_danmaku = QtWidgets.QLabel(self.widget_video_sum)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_video_danmaku.setFont(font)
        self.label_video_danmaku.setAlignment(QtCore.Qt.AlignCenter)
        self.label_video_danmaku.setObjectName("label_video_danmaku")
        self.gridLayout_3.addWidget(self.label_video_danmaku, 2, 0, 1, 1)
        self.label_video_share = QtWidgets.QLabel(self.widget_video_sum)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_video_share.setFont(font)
        self.label_video_share.setAlignment(QtCore.Qt.AlignCenter)
        self.label_video_share.setObjectName("label_video_share")
        self.gridLayout_3.addWidget(self.label_video_share, 2, 1, 1, 1)
        self.label_video_favorite = QtWidgets.QLabel(self.widget_video_sum)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_video_favorite.setFont(font)
        self.label_video_favorite.setAlignment(QtCore.Qt.AlignCenter)
        self.label_video_favorite.setObjectName("label_video_favorite")
        self.gridLayout_3.addWidget(self.label_video_favorite, 2, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.widget_video_sum)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(8)
        self.label_9.setFont(font)
        self.label_9.setScaledContents(False)
        self.label_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_9.setIndent(-1)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 0, 0, 1, 4)
        self.gridLayout_5.addWidget(self.widget_video_sum, 2, 0, 1, 1)
        self.horizontalLayout.addWidget(self.widget_left)
        self.widget_right = QtWidgets.QWidget(self.widget_main)
        self.widget_right.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_right.setStyleSheet("QWidget#widget_right{border-radius:0px;background:Transparent;}")
        self.widget_right.setObjectName("widget_right")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.widget_right)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setSpacing(0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.horizontalLayout.addWidget(self.widget_right)
        self.gridLayout.addWidget(self.widget_main, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 930, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_notify_at.setToolTip(_translate("MainWindow", "<html><head/><body><p>@我的</p></body></html>"))
        self.pushButton_notify_chat.setToolTip(_translate("MainWindow", "<html><head/><body><p>我的消息</p></body></html>"))
        self.pushButton_notify_reply.setToolTip(_translate("MainWindow", "<html><head/><body><p>新的回复</p></body></html>"))
        self.pushButton_notify_like.setToolTip(_translate("MainWindow", "<html><head/><body><p>新的点赞</p></body></html>"))
        self.pushButton_notify_sys_msg.setToolTip(_translate("MainWindow", "<html><head/><body><p>系统通知</p></body></html>"))
        self.pushButton_signout.setToolTip(_translate("MainWindow", "<html><head/><body><p>退出登录</p></body></html>"))
        self.pushButton_close.setToolTip(_translate("MainWindow", "<html><head/><body><p>关闭程序</p></body></html>"))
        self.label_brokerage.setText(_translate("MainWindow", "贝壳\n"
"0"))
        self.label_balance.setText(_translate("MainWindow", "电池\n"
"0"))
        self.label_coins.setText(_translate("MainWindow", "硬币\n"
"0"))
        self.label_default_bp.setText(_translate("MainWindow", "B币\n"
"0"))
        self.label_level_exp.setText(_translate("MainWindow", "0/9999"))
        self.label_level.setText(_translate("MainWindow", "等级："))
        self.pushButton_notify.setText(_translate("MainWindow", "正在初始化..."))
        self.label_article_view.setText(_translate("MainWindow", "阅读\n"
"0"))
        self.label_article_like.setText(_translate("MainWindow", "点赞\n"
"0"))
        self.label_article_coin.setText(_translate("MainWindow", "投币\n"
"0"))
        self.label_article_reply.setText(_translate("MainWindow", "评论\n"
"0"))
        self.label_article_share.setText(_translate("MainWindow", "分享\n"
"0"))
        self.label_article_favorite.setText(_translate("MainWindow", "收藏\n"
"0"))
        self.label_17.setText(_translate("MainWindow", "专栏稿件"))
        self.label_follower.setText(_translate("MainWindow", "粉丝\n"
"0"))
        self.label_creative.setText(_translate("MainWindow", "创作力\n"
"0"))
        self.label_influence.setText(_translate("MainWindow", "影响力\n"
"0"))
        self.label_credit.setText(_translate("MainWindow", "信用分\n"
"0"))
        self.label_video_view.setText(_translate("MainWindow", "播放\n"
"0"))
        self.label_video_like.setText(_translate("MainWindow", "点赞\n"
"0"))
        self.label_video_coin.setText(_translate("MainWindow", "投币\n"
"0"))
        self.label_video_reply.setText(_translate("MainWindow", "评论\n"
"0"))
        self.label_video_danmaku.setText(_translate("MainWindow", "弹幕\n"
"0"))
        self.label_video_share.setText(_translate("MainWindow", "分享\n"
"0"))
        self.label_video_favorite.setText(_translate("MainWindow", "收藏\n"
"0"))
        self.label_9.setText(_translate("MainWindow", "视频稿件"))
import resources_rc
